FROM python:3.9
WORKDIR /app
COPY . .
RUN  apt-get update && apt-get install -y libpq-dev && apt install -y build-essential python3-dev libssl-dev libffi-dev
RUN pip install --upgrade pip && pip install -r requirements.txt
EXPOSE 8000
ENV APP_level=stage_deployment
CMD ["python3","manage.py", "runserver","0.0.0.0:8000"]

